/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_yang_com_ndk_demo_NdkTest */

#ifndef _Included_demo_yang_com_ndk_demo_NdkTest
#define _Included_demo_yang_com_ndk_demo_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_yang_com_ndk_demo_NdkTest
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_yang_com_ndk_1demo_NdkTest_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     demo_yang_com_ndk_demo_NdkTest
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_yang_com_ndk_1demo_NdkTest_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
